import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://services.gst.gov.in/services/login');
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByPlaceholder('{{trans.HLP_USERNAME}}').fill('PASKOHSALES');
  await page.getByRole('textbox', { name: 'Username' }).press('Tab');
  await page.getByRole('textbox', { name: 'Password' }).fill('Bb@1234567891');
  await page.getByRole('textbox', { name: 'Type the characters you see' }).click();
  await page.getByRole('textbox', { name: 'Type the characters you see' }).fill('686013');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.locator('.dimmer-holder').click();
  await page.locator('#dimmer').click();
  await page.locator('select[name="fin"]').selectOption('object:182');
  await page.locator('select[name="quarter"]').selectOption('object:195');
  await page.locator('select[name="mon"]').selectOption('object:199');
  await page.getByRole('button', { name: 'Search', exact: true }).click();
  await page.getByRole('button', { name: 'Download' }).nth(2).click();
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('button', { name: 'GENERATE JSON FILE TO DOWNLOAD' }).click();
  const download = await downloadPromise;
  await page.getByRole('button', { name: 'BACK' }).click();
  await page.locator('select[name="fin"]').selectOption('object:186');
  await page.locator('select[name="quarter"]').selectOption('object:199');
  await page.locator('select[name="mon"]').selectOption('object:204');
  await page.getByRole('button', { name: 'Search', exact: true }).click();
  await page.getByRole('button', { name: 'Download' }).nth(2).click();
  const download1Promise = page.waitForEvent('download');
  await page.getByRole('button', { name: 'GENERATE JSON FILE TO DOWNLOAD' }).click();
  const download1 = await download1Promise;
  await page.getByRole('button', { name: 'BACK' }).click();
  await page.locator('select[name="fin"]').selectOption('object:186');
  await page.locator('select[name="quarter"]').selectOption('object:199');
  await page.getByRole('button', { name: 'Search', exact: true }).click();
  await page.getByRole('button', { name: 'Download' }).nth(2).click();
  const download2Promise = page.waitForEvent('download');
  await page.getByRole('button', { name: 'GENERATE JSON FILE TO DOWNLOAD' }).click();
  const download2 = await download2Promise;
  await page.getByRole('button', { name: 'BACK' }).click();
  await page.locator('div').nth(2).click();
  await page.locator('select[name="fin"]').selectOption('object:186');
  await page.locator('select[name="quarter"]').selectOption('object:200');
  await page.locator('select[name="mon"]').selectOption('object:203');
});